@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.entity.finalcastle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;