@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package twilightforest.client.renderer.entity;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;
