@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.loot.modifiers;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;