@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.world.components.chunkgenerators.warp;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;