@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.client.shader;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;