@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.client.particle;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;