@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.client.particle;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;