@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.compat.curios;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;