@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.capabilities.teleporter_cache;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;