@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.entity.passive;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;