package twilightforest.world.registration;

import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.HugeMushroomBlock;
import twilightforest.block.TFBlocks;
import twilightforest.block.TorchberryPlantBlock;

public final class BlockConstants {
    //Blockstates
    public static final BlockState SPRUCE_LOG = Blocks.SPRUCE_LOG.defaultBlockState();
    public static final BlockState SPRUCE_LEAVES = Blocks.SPRUCE_LEAVES.defaultBlockState();
    public static final BlockState SPRUCE_SAPLING = Blocks.SPRUCE_SAPLING.defaultBlockState();
    public static final BlockState OAK_LOG = Blocks.OAK_LOG.defaultBlockState();
    public static final BlockState OAK_LEAVES = Blocks.OAK_LEAVES.defaultBlockState();
    public static final BlockState OAK_SAPLING = Blocks.OAK_SAPLING.defaultBlockState();
    public static final BlockState TOAK_LOG = TFBlocks.TWILIGHT_OAK_LOG.get().defaultBlockState();
    public static final BlockState TOAK_WOOD = TFBlocks.TWILIGHT_OAK_WOOD.get().defaultBlockState();
    public static final BlockState TOAK_LEAVES = TFBlocks.TWILIGHT_OAK_LEAVES.get().defaultBlockState();
    public static final BlockState TOAK_SAPLING = TFBlocks.TWILIGHT_OAK_SAPLING.get().defaultBlockState();
    public static final BlockState CANOPY_LOG = TFBlocks.CANOPY_LOG.get().defaultBlockState();
    public static final BlockState CANOPY_LEAVES = TFBlocks.CANOPY_LEAVES.get().defaultBlockState();
    public static final BlockState CANOPY_SAPLING = TFBlocks.CANOPY_SAPLING.get().defaultBlockState();
    public static final BlockState MANGROVE_LOG = TFBlocks.MANGROVE_LOG.get().defaultBlockState();
    public static final BlockState MANGROVE_WOOD = TFBlocks.MANGROVE_WOOD.get().defaultBlockState();
    public static final BlockState MANGROVE_LEAVES = TFBlocks.MANGROVE_LEAVES.get().defaultBlockState();
    public static final BlockState MANGROVE_SAPLING = TFBlocks.MANGROVE_SAPLING.get().defaultBlockState();
    public static final BlockState DARKWOOD_LOG = TFBlocks.DARK_LOG.get().defaultBlockState();
    public static final BlockState DARKWOOD_LEAVES = TFBlocks.DARK_LEAVES.get().defaultBlockState();
    public static final BlockState HARDENED_DARK_LEAVES = TFBlocks.HARDENED_DARK_LEAVES.get().defaultBlockState();
    public static final BlockState DARKWOOD_SAPLING = TFBlocks.DARKWOOD_SAPLING.get().defaultBlockState();
    public static final BlockState TIME_LOG = TFBlocks.TIME_LOG.get().defaultBlockState();
    public static final BlockState TIME_WOOD = TFBlocks.TIME_WOOD.get().defaultBlockState();
    public static final BlockState TIME_LEAVES = TFBlocks.TIME_LEAVES.get().defaultBlockState();
    public static final BlockState TRANSFORM_LOG = TFBlocks.TRANSFORMATION_LOG.get().defaultBlockState();
    public static final BlockState TRANSFORM_LEAVES = TFBlocks.TRANSFORMATION_LEAVES.get().defaultBlockState();
    public static final BlockState TRANSFORM_SAPLING = TFBlocks.TRANSFORMATION_SAPLING.get().defaultBlockState();
    public static final BlockState MINING_LOG = TFBlocks.MINING_LOG.get().defaultBlockState();
    public static final BlockState MINING_WOOD = TFBlocks.MINING_WOOD.get().defaultBlockState();
    public static final BlockState MINING_LEAVES = TFBlocks.MINING_LEAVES.get().defaultBlockState();
    public static final BlockState SORT_LOG = TFBlocks.SORTING_LOG.get().defaultBlockState();
    public static final BlockState SORT_LEAVES = TFBlocks.SORTING_LEAVES.get().defaultBlockState();
    public static final BlockState SORT_SAPLING = TFBlocks.SORTING_SAPLING.get().defaultBlockState();
    public static final BlockState RAINBOW_LEAVES = TFBlocks.RAINBOW_OAK_LEAVES.get().defaultBlockState();
    public static final BlockState RAINBOW_SAPLING = TFBlocks.RAINBOW_OAK_SAPLING.get().defaultBlockState();
    public static final BlockState ROOTS = TFBlocks.ROOT_BLOCK.get().defaultBlockState();
    public static final BlockState GRASS = Blocks.GRASS.defaultBlockState();  
    public static final BlockState TALL_GRASS = Blocks.TALL_GRASS.defaultBlockState();  
    public static final BlockState FERN = Blocks.FERN.defaultBlockState();
    public static final BlockState TALL_FERN = Blocks.LARGE_FERN.defaultBlockState();
    public static final BlockState POPPY = Blocks.POPPY.defaultBlockState();
    public static final BlockState DANDELION = Blocks.DANDELION.defaultBlockState();
    public static final BlockState RED_TULIP = Blocks.RED_TULIP.defaultBlockState();
    public static final BlockState ORANGE_TULIP = Blocks.ORANGE_TULIP.defaultBlockState();
    public static final BlockState PINK_TULIP = Blocks.PINK_TULIP.defaultBlockState();
    public static final BlockState WHITE_TULIP = Blocks.WHITE_TULIP.defaultBlockState();
    public static final BlockState ALLIUM = Blocks.ALLIUM.defaultBlockState();
    public static final BlockState AZURE = Blocks.AZURE_BLUET.defaultBlockState();
    public static final BlockState ORCHID = Blocks.BLUE_ORCHID.defaultBlockState();
    public static final BlockState LILY = Blocks.LILY_OF_THE_VALLEY.defaultBlockState();
    public static final BlockState CORNFLOWER = Blocks.CORNFLOWER.defaultBlockState();
    public static final BlockState OXEYE = Blocks.OXEYE_DAISY.defaultBlockState();
    public static final BlockState MAYAPPLE = TFBlocks.MAYAPPLE.get().defaultBlockState();
    public static final BlockState FIDDLEHEAD = TFBlocks.FIDDLEHEAD.get().defaultBlockState();
    public static final BlockState MUSHGLOOM = TFBlocks.MUSHGLOOM.get().defaultBlockState();
    public static final BlockState FIRE_JET = TFBlocks.FIRE_JET.get().defaultBlockState();
    public static final BlockState SMOKER = TFBlocks.SMOKER.get().defaultBlockState();
    public static final BlockState AIR = Blocks.AIR.defaultBlockState();
    public static final BlockState MYCELIUM = Blocks.MYCELIUM.defaultBlockState();
    public static final BlockState UBEROUS_SOIL = TFBlocks.UBEROUS_SOIL.get().defaultBlockState();
    public static final BlockState DIRT = Blocks.DIRT.defaultBlockState();
    public static final BlockState SAND = Blocks.SAND.defaultBlockState();
    public static final BlockState STONE = Blocks.STONE.defaultBlockState();
    public static final BlockState GRASS_BLOCK = Blocks.GRASS_BLOCK.defaultBlockState();
    public static final BlockState PODZOL = Blocks.PODZOL.defaultBlockState();
    public static final BlockState COARSE_DIRT = Blocks.COARSE_DIRT.defaultBlockState();
    public static final BlockState FIREFLY_JAR = TFBlocks.FIREFLY_JAR.get().defaultBlockState();
    public static final BlockState TROLLVIDR = TFBlocks.TROLLVIDR.get().defaultBlockState();
    public static final BlockState TORCHBERRIES = TFBlocks.TORCHBERRY_PLANT.get().defaultBlockState().setValue(TorchberryPlantBlock.HAS_BERRIES, true);
    public static final BlockState ROOT_STRAND = TFBlocks.ROOT_STRAND.get().defaultBlockState();
    public static final BlockState HANGING_ROOTS = Blocks.HANGING_ROOTS.defaultBlockState();
    public static final BlockState PUMPKIN = Blocks.PUMPKIN.defaultBlockState();
    public static final BlockState DEAD_BUSH = Blocks.DEAD_BUSH.defaultBlockState();
    public static final BlockState BROWN_MUSHROOM = Blocks.BROWN_MUSHROOM.defaultBlockState();
    public static final BlockState RED_MUSHROOM = Blocks.RED_MUSHROOM.defaultBlockState();
    public static final BlockState JACK_O_LANTERN = Blocks.JACK_O_LANTERN.defaultBlockState();
    public static final BlockState DEADROCK = TFBlocks.DEADROCK.get().defaultBlockState();
    public static final BlockState WEATHERED_DEADROCK = TFBlocks.WEATHERED_DEADROCK.get().defaultBlockState();
    public static final BlockState CRACKED_DEADROCK = TFBlocks.CRACKED_DEADROCK.get().defaultBlockState();
    public static final BlockState SNOW = Blocks.SNOW_BLOCK.defaultBlockState();
    public static final BlockState POWDER_SNOW = Blocks.POWDER_SNOW.defaultBlockState();
    public static final BlockState ICE = Blocks.ICE.defaultBlockState();
    public static final BlockState PACKED_ICE = Blocks.PACKED_ICE.defaultBlockState();
    public static final BlockState MUSHROOM_STEM = Blocks.MUSHROOM_STEM.defaultBlockState();//.with(HugeMushroomBlock.UP, true).with(HugeMushroomBlock.DOWN, false).with(HugeMushroomBlock.NORTH, true).with(HugeMushroomBlock.SOUTH, true).with(HugeMushroomBlock.WEST, true).with(HugeMushroomBlock.EAST, true);
    public static final BlockState MUSHROOM_CAP_RED = Blocks.RED_MUSHROOM_BLOCK.defaultBlockState().setValue(HugeMushroomBlock.DOWN, false);//.with(HugeMushroomBlock.UP, true).with(HugeMushroomBlock.NORTH, true).with(HugeMushroomBlock.SOUTH, true).with(HugeMushroomBlock.WEST, true).with(HugeMushroomBlock.EAST, true);
    public static final BlockState MUSHROOM_CAP_BROWN = Blocks.BROWN_MUSHROOM_BLOCK.defaultBlockState().setValue(HugeMushroomBlock.DOWN, false);//.with(HugeMushroomBlock.UP, true).with(HugeMushroomBlock.NORTH, true).with(HugeMushroomBlock.SOUTH, true).with(HugeMushroomBlock.WEST, true).with(HugeMushroomBlock.EAST, true);
}
