@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.world.registration;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;