// Date: 2/5/2012 10:11:18 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package twilightforest.client.model.entity.legacy;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;
import twilightforest.entity.boss.Hydra;
import twilightforest.entity.boss.HydraPart;

public class HydraLegacyModel extends HierarchicalModel<Hydra> {
	//fields
	final ModelPart root;
	final ModelPart body;
	ModelPart tail;
	ModelPart leg1;
	ModelPart leg2;

	public HydraLegacyModel(ModelPart root) {
		this.root = root;
		this.body = root.getChild("body");
		this.tail = root.getChild("tail_1");
		this.leg1 = root.getChild("leg_1");
		this.leg2 = root.getChild("leg_2");
	}

	public static LayerDefinition create() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition partRoot = mesh.getRoot();

		partRoot.addOrReplaceChild("body", CubeListBuilder.create()
						.texOffs(0, 0)
						.addBox(-48F, 0F, 0F, 96, 96, 40),
				PartPose.offsetAndRotation(0F, -12F, 0F, 1.22173F, 0F, 0F));

		partRoot.addOrReplaceChild("leg_1", CubeListBuilder.create()
						.texOffs(0, 136)
						.addBox(-16F, 0F, -16F, 32, 48, 32)
						.texOffs(184, 200)
						.addBox(-20F, 40F, -20F, 8, 8, 8)
						.texOffs(184, 200)
						.addBox(-4F, 40F, -22F, 8, 8, 8)
						.texOffs(184, 200)
						.addBox(12F, 40F, -20F, 8, 8, 8),
				PartPose.offset(48F, -24F, 0F));

		partRoot.addOrReplaceChild("leg_2", CubeListBuilder.create().mirror()
						.texOffs(0, 136)
						.addBox(-16F, 0F, -16F, 32, 48, 32)
						.texOffs(184, 200)
						.addBox(-20F, 40F, -20F, 8, 8, 8)
						.texOffs(184, 200)
						.addBox(-4F, 40F, -22F, 8, 8, 8)
						.texOffs(184, 200)
						.addBox(12F, 40F, -20F, 8, 8, 8),
				PartPose.offset(-48F, -24F, 0F));

		var tail1 = partRoot.addOrReplaceChild("tail_1", CubeListBuilder.create()
						.texOffs(128, 136)
						.addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200)
						.addBox(-2F, -28F, -11F, 4, 24, 24),
				PartPose.offset(0F, 6F, 108F));

		var tail2 = tail1.addOrReplaceChild("tail_2", CubeListBuilder.create()
						.texOffs(128, 136)
						.addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200)
						.addBox(-2F, -28F, -11F, 4, 24, 24),
				PartPose.offset(0F, 0F, 32F));

		var tail3 = tail2.addOrReplaceChild("tail_3", CubeListBuilder.create()
						.texOffs(128, 136)
						.addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200)
						.addBox(-2F, -28F, -11F, 4, 24, 24),
				PartPose.offset(0F, 0F, 32F));

		tail3.addOrReplaceChild("tail_4", CubeListBuilder.create()
						.texOffs(128, 136)
						.addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200)
						.addBox(-2F, -28F, -11F, 4, 24, 24),
				PartPose.offset(0F, 0F, 32F));

		var head1 = partRoot.addOrReplaceChild("head_1", CubeListBuilder.create()
						.texOffs(272, 0)
						.addBox(-16F, -14F, -32F, 32, 24, 32)
						.texOffs(272, 56)
						.addBox(-15F, -2F, -56F, 30, 12, 24)
						.texOffs(128, 200)
						.addBox(-2F, -30F, -12F, 4, 24, 24),
				PartPose.offset(0F, -128F, -53F));

		head1.addOrReplaceChild("jaw_1", CubeListBuilder.create()
						.texOffs(272, 92)
						.addBox(-15F, 0F, -48F, 30, 8, 48),
				PartPose.offset(0F, 10F, -4F));

		head1.addOrReplaceChild("frill_1", CubeListBuilder.create()
						.texOffs(272, 200)
						.addBox(-24F, -40.0F, 0F, 48, 48, 4),
				PartPose.offsetAndRotation(0F, 0F, -10F, -0.5235988F, 0F, 0F));

		partRoot.addOrReplaceChild("neck_1a", CubeListBuilder.create()
						.texOffs(128, 136).addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200).addBox(-2F, -23F, 0F, 4, 24, 24),
				PartPose.offset(0F, -48F, 16F));

		partRoot.addOrReplaceChild("neck_1b", CubeListBuilder.create()
						.texOffs(128, 136).addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200).addBox(-2F, -23F, 0F, 4, 24, 24),
				PartPose.offset(0F, -68F, 0F));

		partRoot.addOrReplaceChild("neck_1c", CubeListBuilder.create()
						.texOffs(128, 136).addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200).addBox(-2F, -23F, 0F, 4, 24, 24),
				PartPose.offset(0F, -93F, -14F));

		partRoot.addOrReplaceChild("neck_1d", CubeListBuilder.create()
						.texOffs(128, 136).addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200).addBox(-2F, -23F, 0F, 4, 24, 24),
				PartPose.offset(0F, -116F, -37F));

		var head2 = partRoot.addOrReplaceChild("head_2", CubeListBuilder.create()
						.texOffs(272, 0)
						.addBox(-16F, -14F, -32F, 32, 24, 32)
						.texOffs(272, 56)
						.addBox(-15F, -2F, -56F, 30, 12, 24)
						.texOffs(128, 200)
						.addBox(-2F, -30F, -12F, 4, 24, 24),
				PartPose.offset(108F, -128F, -53F));

		head2.addOrReplaceChild("jaw_2", CubeListBuilder.create()
						.texOffs(272, 92)
						.addBox(-15F, 0F, -48F, 30, 8, 48),
				PartPose.offset(0F, 10F, -4F));

		head2.addOrReplaceChild("frill_2", CubeListBuilder.create()
						.texOffs(272, 200)
						.addBox(-24F, -40.0F, 0F, 48, 48, 4),
				PartPose.offsetAndRotation(0F, 0F, -10F, -0.5235988F, 0F, 0F));

		partRoot.addOrReplaceChild("neck_2a", CubeListBuilder.create()
						.texOffs(128, 136).addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200).addBox(-2F, -23F, 0F, 4, 24, 24),
				PartPose.offset(48F, -48F, 16F));

		partRoot.addOrReplaceChild("neck_2b", CubeListBuilder.create()
						.texOffs(128, 136).addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200).addBox(-2F, -23F, 0F, 4, 24, 24),
				PartPose.offset(71F, -68F, 0F));

		partRoot.addOrReplaceChild("neck_2c", CubeListBuilder.create()
						.texOffs(128, 136).addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200).addBox(-2F, -23F, 0F, 4, 24, 24),
				PartPose.offset(96F, -93F, -14F));

		partRoot.addOrReplaceChild("neck_2d", CubeListBuilder.create()
						.texOffs(128, 136).addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200).addBox(-2F, -23F, 0F, 4, 24, 24),
				PartPose.offset(108F, -116F, -37F));

		var head3 = partRoot.addOrReplaceChild("head_3", CubeListBuilder.create()
						.texOffs(272, 0)
						.addBox(-16F, -14F, -32F, 32, 24, 32)
						.texOffs(272, 56)
						.addBox(-15F, -2F, -56F, 30, 12, 24)
						.texOffs(128, 200)
						.addBox(-2F, -30F, -12F, 4, 24, 24),
				PartPose.offset(-108F, -24F, -53F));

		head3.addOrReplaceChild("jaw_3", CubeListBuilder.create()
						.texOffs(272, 92)
						.addBox(-15F, 0F, -48F, 30, 8, 48),
				PartPose.offset(0F, 10F, -4F));

		head3.addOrReplaceChild("frill_3", CubeListBuilder.create()
						.texOffs(272, 200)
						.addBox(-24F, -40.0F, 0F, 48, 48, 4),
				PartPose.offsetAndRotation(0F, 0F, -10F, -0.5235988F, 0F, 0F));

		partRoot.addOrReplaceChild("neck_3a", CubeListBuilder.create()
						.texOffs(128, 136).addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200).addBox(-2F, -23F, 0F, 4, 24, 24),
				PartPose.offset(-48F, -48F, 16F));

		partRoot.addOrReplaceChild("neck_3b", CubeListBuilder.create()
						.texOffs(128, 136).addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200).addBox(-2F, -23F, 0F, 4, 24, 24),
				PartPose.offset(-71F, -43F, 0F));

		partRoot.addOrReplaceChild("neck_3c", CubeListBuilder.create()
						.texOffs(128, 136).addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200).addBox(-2F, -23F, 0F, 4, 24, 24),
				PartPose.offset(-96F, -33F, -14F));

		partRoot.addOrReplaceChild("neck_3d", CubeListBuilder.create()
						.texOffs(128, 136).addBox(-16F, -16F, -16F, 32, 32, 32)
						.texOffs(128, 200).addBox(-2F, -23F, 0F, 4, 24, 24),
				PartPose.offset(-108F, -24F, -37F));

		return LayerDefinition.create(mesh, 512, 256);
	}

	@Override
	public ModelPart root() {
		return this.root;
	}

	@Override
	public void renderToBuffer(PoseStack p_170625_, VertexConsumer p_170626_, int p_170627_, int p_170628_, float p_170629_, float p_170630_, float p_170631_, float p_170632_) {
		this.leg1.render(p_170625_, p_170626_, p_170627_, p_170628_, p_170629_, p_170630_, p_170631_, p_170632_);
		this.leg2.render(p_170625_, p_170626_, p_170627_, p_170628_, p_170629_, p_170630_, p_170631_, p_170632_);
		this.body.render(p_170625_, p_170626_, p_170627_, p_170628_, p_170629_, p_170630_, p_170631_, p_170632_);
		this.tail.render(p_170625_, p_170626_, p_170627_, p_170628_, p_170629_, p_170630_, p_170631_, p_170632_);

	}

	@Override
	public void setupAnim(Hydra entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
		//super.setRotationAngles(entity, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scaleFactor);

		leg1.xRot = Mth.cos(limbSwing * 0.6662F) * 1.4F * limbSwingAmount;
		leg2.xRot = Mth.cos(limbSwing * 0.6662F + 3.141593F) * 1.4F * limbSwingAmount;

		leg1.yRot = 0.0F;
		leg2.yRot = 0.0F;
	}

    public float getRotationY(Hydra hydra, HydraPart whichHead, float time) {

		float yawOffset = hydra.yBodyRotO + (hydra.yBodyRot - hydra.yBodyRotO) * time;
		float yaw = whichHead.yRotO + (whichHead.getYRot() - whichHead.yRotO) * time;

		return (yaw - yawOffset) / 57.29578F;
	}

	public float getRotationX(Hydra hydra, HydraPart whichHead, float time) {

		return (whichHead.xRotO + (whichHead.getXRot() - whichHead.xRotO) * time) / 57.29578F;
	}
}
