// Date: 11/5/2012 7:35:56 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package twilightforest.client.model.entity.legacy;

import com.google.common.collect.ImmutableList;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.ListModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.util.Mth;
import twilightforest.entity.SlimeBeetleEntity;

public class SlimeBeetleLegacyModel extends ListModel<SlimeBeetleEntity> {
	ModelPart head;
	ModelPart RearEnd;
	ModelPart Leg6;
	ModelPart Leg4;
	ModelPart Leg2;
	ModelPart Leg5;
	ModelPart Leg3;
	ModelPart Leg1;
	ModelPart connector1;
	ModelPart antenna1;
	ModelPart antenna2;
	ModelPart eye1;
	ModelPart eye2;

	ModelPart slimeCube;
	ModelPart tail1;
	ModelPart tail2;
	ModelPart mouth;
	ModelPart slimeCenter;

	private final boolean translucent;

	public SlimeBeetleLegacyModel() {
		this(false);
	}

	public SlimeBeetleLegacyModel(boolean translucent) {
		this.translucent = translucent;

		texWidth = 64;
		texHeight = 64;

		connector1 = new ModelPart(this, 0, 12);
		connector1.addBox(-3F, -3F, -1F, 6, 6, 1);
		connector1.setPos(0F, 19F, -4F);

		RearEnd = new ModelPart(this, 31, 6);
		RearEnd.addBox(-4F, -11F, -4F, 8, 10, 8);
		RearEnd.setPos(0F, 18F, 7F);
		setRotation(RearEnd, 1.570796F, 0F, 0F);

		Leg6 = new ModelPart(this, 40, 0);
		Leg6.addBox(-1F, -1F, -1F, 10, 2, 2);
		Leg6.setPos(2F, 21F, -4F);
		setRotation(Leg6, 0F, 0.2792527F, 0.3490659F);

		Leg5 = new ModelPart(this, 40, 0);
		Leg5.mirror = true;
		Leg5.addBox(-9F, -1F, -1F, 10, 2, 2);
		Leg5.setPos(-2F, 21F, -4F);
		setRotation(Leg5, 0F, -0.2792527F, -0.3490659F);

		Leg4 = new ModelPart(this, 40, 0);
		Leg4.addBox(-1F, -1F, -1F, 10, 2, 2);
		Leg4.setPos(2F, 21F, -1F);
		setRotation(Leg4, 0F, -0.2792527F, 0.3490659F);

		Leg2 = new ModelPart(this, 40, 0);
		Leg2.addBox(-1F, -1F, -1F, 10, 2, 2);
		Leg2.setPos(2F, 21F, 4F);
		setRotation(Leg2, 0F, -0.6981317F, 0.3490659F);

		Leg3 = new ModelPart(this, 40, 0);
		Leg3.mirror = true;
		Leg3.addBox(-9F, -1F, -1F, 10, 2, 2);
		Leg3.setPos(-2F, 21F, -1F);
		setRotation(Leg3, 0F, 0.2792527F, -0.3490659F);

		Leg1 = new ModelPart(this, 40, 0);
		Leg1.mirror = true;
		Leg1.addBox(-9F, -1F, -1F, 10, 2, 2);
		Leg1.setPos(-2F, 21F, 4F);
		Leg1.setTexSize(64, 32);
		setRotation(Leg1, 0F, 0.6981317F, -0.3490659F);

		head = new ModelPart(this, 0, 0);
		head.addBox(-4F, -4F, -6F, 8, 6, 6);
		head.setPos(0F, 19F, -5F);

		antenna1 = new ModelPart(this, 38, 4);
		antenna1.addBox(0F, -0.5F, -0.5F, 12, 1, 1);
		antenna1.setPos(1F, -3F, -5F);
		setRotation(antenna1, 0F, 1.047198F, -0.296706F);

		antenna2 = new ModelPart(this, 38, 4);
		antenna2.addBox(0F, -0.5F, -0.5F, 12, 1, 1);
		antenna2.setPos(-1F, -3F, -5F);
		setRotation(antenna2, 0F, 2.094395F, 0.296706F);

		eye1 = new ModelPart(this, 15, 12);
		eye1.addBox(-1.5F, -1.5F, -1.5F, 3, 3, 3);
		eye1.setPos(-3F, -2F, -5F);

		eye2 = new ModelPart(this, 15, 12);
		eye2.addBox(-1.5F, -1.5F, -1.5F, 3, 3, 3);
		eye2.setPos(3F, -2F, -5F);

		mouth = new ModelPart(this, 17, 12);
		mouth.addBox(-1F, -1F, -1F, 2, 2, 1);
		mouth.setPos(0F, 1, -6F);

		head.addChild(antenna1);
		head.addChild(antenna2);
		head.addChild(eye1);
		head.addChild(eye2);
		head.addChild(mouth);

		tail1 = new ModelPart(this, 0, 20);
		tail1.addBox(-3F, -3F, -3F, 6, 6, 6);
		tail1.setPos(0F, 19F, 9F);

		tail2 = new ModelPart(this, 0, 20);
		tail2.addBox(-3F, -6F, -3F, 6, 6, 6);
		tail2.setPos(0F, -3F, 2F);

		slimeCube = new ModelPart(this, 0, 40);
		slimeCube.addBox(-6F, -12F, -9F, 12, 12, 12);
		slimeCube.setPos(0F, -6, 0);

		slimeCenter = new ModelPart(this, 32, 24);
		slimeCenter.addBox(-4F, -10F, -7F, 8, 8, 8);
		slimeCenter.setPos(0F, -6, 0);

		tail1.addChild(tail2);

		if (this.translucent) {
			tail2.addChild(slimeCube);
		} else {
			tail2.addChild(slimeCenter);
		}
	}

	@Override
	public Iterable<ModelPart> parts() {
		return ImmutableList.of(
				head,
				RearEnd,
				Leg6,
				Leg4,
				Leg2,
				Leg5,
				Leg3,
				Leg1,
				connector1
		);
	}

	@Override
	public void renderToBuffer(PoseStack stack, VertexConsumer builder, int light, int overlay, float red, float green, float blue, float alpha) {
		tail1.render(stack, builder, light, overlay, red, green, blue, alpha);

		if (!translucent) {
			parts().forEach((part) -> part.render(stack, builder, light, overlay, red, green, blue, alpha));
		}
	}

	private void setRotation(ModelPart model, float x, float y, float z) {
		model.xRot = x;
		model.yRot = y;
		model.zRot = z;
	}

	@Override
	public void setupAnim(SlimeBeetleEntity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
		this.head.yRot = netHeadYaw / (180F / (float) Math.PI);
		this.head.xRot = headPitch / (180F / (float) Math.PI);

		// legs!
		float legZ = ((float) Math.PI / 11F);
		this.Leg1.zRot = -legZ;
		this.Leg2.zRot = legZ;
		this.Leg3.zRot = -legZ * 0.74F;
		this.Leg4.zRot = legZ * 0.74F;
		this.Leg5.zRot = -legZ;
		this.Leg6.zRot = legZ;

		float var9 = -0.0F;
		float var10 = 0.3926991F;
		this.Leg1.yRot = var10 * 2.0F + var9;
		this.Leg2.yRot = -var10 * 2.0F - var9;
		this.Leg3.yRot = var10 + var9;
		this.Leg4.yRot = -var10 - var9;
		this.Leg5.yRot = -var10 * 2.0F + var9;
		this.Leg6.yRot = var10 * 2.0F - var9;

		float var11 = -(Mth.cos(limbSwing * 0.6662F * 2.0F + 0.0F) * 0.4F) * limbSwingAmount;
		float var12 = -(Mth.cos(limbSwing * 0.6662F * 2.0F + (float) Math.PI) * 0.4F) * limbSwingAmount;
		float var14 = -(Mth.cos(limbSwing * 0.6662F * 2.0F + ((float) Math.PI * 3F / 2F)) * 0.4F) * limbSwingAmount;

		float var15 = Math.abs(Mth.sin(limbSwing * 0.6662F + 0.0F) * 0.4F) * limbSwingAmount;
		float var16 = Math.abs(Mth.sin(limbSwing * 0.6662F + (float) Math.PI) * 0.4F) * limbSwingAmount;
		float var18 = Math.abs(Mth.sin(limbSwing * 0.6662F + ((float) Math.PI * 3F / 2F)) * 0.4F) * limbSwingAmount;

		this.Leg1.yRot += var11;
		this.Leg2.yRot += -var11;
		this.Leg3.yRot += var12;
		this.Leg4.yRot += -var12;
		this.Leg5.yRot += var14;
		this.Leg6.yRot += -var14;

		this.Leg1.zRot += var15;
		this.Leg2.zRot += -var15;

		this.Leg3.zRot += var16;
		this.Leg4.zRot += -var16;

		this.Leg5.zRot += var18;
		this.Leg6.zRot += -var18;

		// tail wiggle
		this.tail1.xRot = Mth.cos(ageInTicks * 0.3335F) * 0.15F;
		this.tail2.xRot = Mth.cos(ageInTicks * 0.4445F) * 0.20F;
		this.slimeCube.xRot = Mth.cos(ageInTicks * 0.5555F) * 0.25F;
		this.slimeCenter.xRot = Mth.cos(ageInTicks * 0.5555F + 0.25F) * 0.25F;
	}
}
