package twilightforest.item;

import net.minecraft.init.MobEffects;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.potion.PotionEffect;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.registry.IForgeRegistry;
import twilightforest.TwilightForestMod;

import static twilightforest.item.TFItems.*;

@Mod.EventBusSubscriber()
public class TFRegisterItemEvent {
    public static void onRegisterItems(RegistryEvent.Register<Item> event) {
        ItemRegistryHelper items = new ItemRegistryHelper(event.getRegistry());

        Item nagaScale = new ItemTF().setUnlocalizedName("nagaScale");
        Item plateNaga = new ItemTFNagaArmor(ARMOR_NAGA, EntityEquipmentSlot.CHEST).setUnlocalizedName("plateNaga").setMaxStackSize(1);
        Item legsNaga = new ItemTFNagaArmor(ARMOR_NAGA, EntityEquipmentSlot.LEGS).setUnlocalizedName("legsNaga").setMaxStackSize(1);
        Item scepterTwilight = new ItemTFTwilightWand().setUnlocalizedName("scepterTwilight").setMaxStackSize(1);
        Item scepterLifeDrain = new ItemTFScepterLifeDrain().setUnlocalizedName("scepterLifeDrain").setMaxStackSize(1);
        Item scepterZombie = new ItemTFZombieWand().setUnlocalizedName("scepterZombie").setMaxStackSize(1);
        //Item wandPacification = new ItemTF().setIconIndex(6).setUnlocalizedName("wandPacification").setMaxStackSize(1);
        Item oreMeter = new ItemTFOreMeter().setUnlocalizedName("oreMeter").setMaxStackSize(1);
        Item magicMap = new ItemTFMagicMap().setUnlocalizedName("magicMap").setMaxStackSize(1);
        Item mazeMap = new ItemTFMazeMap(false).setUnlocalizedName("mazeMap").setMaxStackSize(1);
        Item oreMap = new ItemTFMazeMap(true).setUnlocalizedName("oreMap").setMaxStackSize(1);
        Item feather = new ItemTF().setUnlocalizedName("tfFeather");
        Item magicMapFocus = new ItemTF().setUnlocalizedName("magicMapFocus");
        Item mazeMapFocus = new ItemTF().setUnlocalizedName("mazeMapFocus");
        Item liveRoot = new ItemTF().setUnlocalizedName("liveRoot");
        Item ironwoodRaw = new ItemTF().setUnlocalizedName("ironwoodRaw");
        Item ironwoodIngot = new ItemTF().setUnlocalizedName("ironwoodIngot");
        Item ironwoodHelm = new ItemTFIronwoodArmor(ARMOR_IRONWOOD, EntityEquipmentSlot.HEAD).setUnlocalizedName("ironwoodHelm").setMaxStackSize(1);
        Item ironwoodPlate = new ItemTFIronwoodArmor(ARMOR_IRONWOOD, EntityEquipmentSlot.CHEST).setUnlocalizedName("ironwoodPlate").setMaxStackSize(1);
        Item ironwoodLegs = new ItemTFIronwoodArmor(ARMOR_IRONWOOD, EntityEquipmentSlot.LEGS).setUnlocalizedName("ironwoodLegs").setMaxStackSize(1);
        Item ironwoodBoots = new ItemTFIronwoodArmor(ARMOR_IRONWOOD, EntityEquipmentSlot.FEET).setUnlocalizedName("ironwoodBoots").setMaxStackSize(1);
        Item ironwoodSword = new ItemTFIronwoodSword(TOOL_IRONWOOD).setUnlocalizedName("ironwoodSword").setMaxStackSize(1);
        Item ironwoodShovel = new ItemTFIronwoodShovel(TOOL_IRONWOOD).setUnlocalizedName("ironwoodShovel").setMaxStackSize(1);
        Item ironwoodPick = new ItemTFIronwoodPick(TOOL_IRONWOOD).setUnlocalizedName("ironwoodPick").setMaxStackSize(1);
        Item ironwoodAxe = new ItemTFIronwoodAxe(TOOL_IRONWOOD).setUnlocalizedName("ironwoodAxe").setMaxStackSize(1);
        Item ironwoodHoe = new ItemTFIronwoodHoe(TOOL_IRONWOOD).setUnlocalizedName("ironwoodHoe").setMaxStackSize(1);
        Item torchberries = new ItemTF().setUnlocalizedName("torchberries");
        Item venisonRaw = (new ItemTFFood(3, 0.3F, true)).setUnlocalizedName("venisonRaw");
        Item venisonCooked = (new ItemTFFood(8, 0.8F, true)).setUnlocalizedName("venisonCooked");
        Item hydraChop = (new ItemTFHydraChops(18, 2.0F, true)).setPotionEffect(new PotionEffect(MobEffects.REGENERATION, 100, 0), 1.0F).setUnlocalizedName("hydraChop");
        Item fieryBlood = new ItemTF().makeRare().setUnlocalizedName("fieryBlood");
        Item trophy = new ItemTFTrophy().setUnlocalizedName("trophy");
        Item fieryIngot = new ItemTF().makeRare().setUnlocalizedName("fieryIngot");
        Item fieryHelm = new ItemTFFieryArmor(ARMOR_FIERY, EntityEquipmentSlot.HEAD).setUnlocalizedName("fieryHelm").setMaxStackSize(1);
        Item fieryPlate = new ItemTFFieryArmor(ARMOR_FIERY, EntityEquipmentSlot.CHEST).setUnlocalizedName("fieryPlate").setMaxStackSize(1);
        Item fieryLegs = new ItemTFFieryArmor(ARMOR_FIERY, EntityEquipmentSlot.LEGS).setUnlocalizedName("fieryLegs").setMaxStackSize(1);
        Item fieryBoots = new ItemTFFieryArmor(ARMOR_FIERY, EntityEquipmentSlot.FEET).setUnlocalizedName("fieryBoots").setMaxStackSize(1);
        Item fierySword = new ItemTFFierySword(TOOL_FIERY).setUnlocalizedName("fierySword").setMaxStackSize(1);
        Item fieryPick = new ItemTFFieryPick(TOOL_FIERY).setUnlocalizedName("fieryPick").setMaxStackSize(1);
        Item steeleafIngot = new ItemTF().setUnlocalizedName("steeleafIngot");
        Item steeleafHelm = new ItemTFSteeleafArmor(ARMOR_IRONWOOD, EntityEquipmentSlot.HEAD).setUnlocalizedName("steeleafHelm").setMaxStackSize(1);
        Item steeleafPlate = new ItemTFSteeleafArmor(ARMOR_IRONWOOD, EntityEquipmentSlot.CHEST).setUnlocalizedName("steeleafPlate").setMaxStackSize(1);
        Item steeleafLegs = new ItemTFSteeleafArmor(ARMOR_IRONWOOD, EntityEquipmentSlot.LEGS).setUnlocalizedName("steeleafLegs").setMaxStackSize(1);
        Item steeleafBoots = new ItemTFSteeleafArmor(ARMOR_IRONWOOD, EntityEquipmentSlot.FEET).setUnlocalizedName("steeleafBoots").setMaxStackSize(1);
        Item steeleafSword = new ItemTFSteeleafSword(TOOL_STEELEAF).setUnlocalizedName("steeleafSword").setMaxStackSize(1);
        Item steeleafShovel = new ItemTFSteeleafShovel(TOOL_STEELEAF).setUnlocalizedName("steeleafShovel").setMaxStackSize(1);
        Item steeleafPick = new ItemTFSteeleafPick(TOOL_STEELEAF).setUnlocalizedName("steeleafPick").setMaxStackSize(1);
        Item steeleafAxe = new ItemTFSteeleafAxe(TOOL_STEELEAF).setUnlocalizedName("steeleafAxe").setMaxStackSize(1);
        Item steeleafHoe = new ItemTFSteeleafHoe(TOOL_STEELEAF).setUnlocalizedName("steeleafHoe").setMaxStackSize(1);
        Item minotaurAxe = new ItemTFMinotaurAxe(Item.ToolMaterial.DIAMOND).setUnlocalizedName("minotaurAxe").setMaxStackSize(1);
        Item mazebreakerPick = new ItemTFMazebreakerPick(Item.ToolMaterial.DIAMOND).setUnlocalizedName("mazebreakerPick").setMaxStackSize(1);
        Item transformPowder = new ItemTFTransformPowder().makeRare().setUnlocalizedName("transformPowder");
        Item meefRaw = (new ItemTFFood(2, 0.3F, true)).setUnlocalizedName("meefRaw");
        Item meefSteak = (new ItemTFFood(6, 0.6F, true)).setUnlocalizedName("meefSteak");
        Item meefStroganoff = (new ItemTFSoup(8)).setUnlocalizedName("meefStroganoff");
        Item mazeWafer = (new ItemTFFood(4, 0.6F, false)).setUnlocalizedName("mazeWafer");
        Item emptyMagicMap = (new ItemTFEmptyMagicMap()).setUnlocalizedName("emptyMagicMap");
        Item emptyMazeMap = (new ItemTFEmptyMazeMap(false)).setUnlocalizedName("emptyMazeMap");
        Item emptyOreMap = (new ItemTFEmptyMazeMap(true)).setUnlocalizedName("emptyOreMap");
        Item oreMagnet = (new ItemTFOreMagnet()).setUnlocalizedName("oreMagnet");
        Item crumbleHorn = (new ItemTFCrumbleHorn()).setUnlocalizedName("crumbleHorn");
        Item peacockFan = (new ItemTFPeacockFan()).setUnlocalizedName("peacockFan");
        Item moonwormQueen = (new ItemTFMoonwormQueen()).setUnlocalizedName("moonwormQueen");
        Item charmOfLife1 = new ItemTFCharm().setUnlocalizedName("charmOfLife1");
        Item charmOfLife2 = new ItemTFCharm().setUnlocalizedName("charmOfLife2");
        Item charmOfKeeping1 = new ItemTFCharm().setUnlocalizedName("charmOfKeeping1");
        Item charmOfKeeping2 = new ItemTFCharm().setUnlocalizedName("charmOfKeeping2");
        Item charmOfKeeping3 = new ItemTFCharm().setUnlocalizedName("charmOfKeeping3");
        Item towerKey = new ItemTFTowerKey().setUnlocalizedName("towerKey");
        Item borerEssence = new ItemTF().setUnlocalizedName("borerEssence");
        Item carminite = new ItemTF().makeRare().setUnlocalizedName("carminite");
        Item experiment115 = (new ItemTFFood(4, 0.3F, false)).setUnlocalizedName("experiment115");
        Item armorShard = new ItemTF().setUnlocalizedName("armorShards");
        Item knightMetal = new ItemTF().setUnlocalizedName("knightMetal");
        Item shardCluster = new ItemTF().setUnlocalizedName("shardCluster");
        Item knightlyHelm = new ItemTFKnightlyArmor(ARMOR_KNIGHTLY, EntityEquipmentSlot.HEAD).setUnlocalizedName("knightlyHelm").setMaxStackSize(1);
        Item knightlyPlate = new ItemTFKnightlyArmor(ARMOR_KNIGHTLY, EntityEquipmentSlot.CHEST).setUnlocalizedName("knightlyPlate").setMaxStackSize(1);
        Item knightlyLegs = new ItemTFKnightlyArmor(ARMOR_KNIGHTLY, EntityEquipmentSlot.LEGS).setUnlocalizedName("knightlyLegs").setMaxStackSize(1);
        Item knightlyBoots = new ItemTFKnightlyArmor(ARMOR_KNIGHTLY, EntityEquipmentSlot.FEET).setUnlocalizedName("knightlyBoots").setMaxStackSize(1);
        Item knightlySword = new ItemTFKnightlySword(TOOL_KNIGHTLY).setUnlocalizedName("knightlySword").setMaxStackSize(1);
        Item knightlyPick = new ItemTFKnightlyPick(TOOL_KNIGHTLY).setUnlocalizedName("knightlyPick").setMaxStackSize(1);
        Item knightlyAxe = new ItemTFKnightlyAxe(TOOL_KNIGHTLY).setUnlocalizedName("knightlyAxe").setMaxStackSize(1);
        Item phantomHelm = new ItemTFPhantomArmor(ARMOR_PHANTOM, EntityEquipmentSlot.HEAD).setUnlocalizedName("phantomHelm").setMaxStackSize(1);
        Item phantomPlate = new ItemTFPhantomArmor(ARMOR_PHANTOM, EntityEquipmentSlot.CHEST).setUnlocalizedName("phantomPlate").setMaxStackSize(1);
        Item lampOfCinders = new ItemTFLampOfCinders().setUnlocalizedName("lampOfCinders");
        Item fieryTears = new ItemTF().makeRare().setUnlocalizedName("fieryTears");
        Item alphaFur = new ItemTF().makeRare().setUnlocalizedName("alphaFur");
        Item yetiHelm = new ItemTFYetiArmor(ARMOR_YETI, EntityEquipmentSlot.HEAD).setUnlocalizedName("yetiHelm").setMaxStackSize(1);
        Item yetiPlate = new ItemTFYetiArmor(ARMOR_YETI, EntityEquipmentSlot.CHEST).setUnlocalizedName("yetiPlate").setMaxStackSize(1);
        Item yetiLegs = new ItemTFYetiArmor(ARMOR_YETI, EntityEquipmentSlot.LEGS).setUnlocalizedName("yetiLegs").setMaxStackSize(1);
        Item yetiBoots = new ItemTFYetiArmor(ARMOR_YETI, EntityEquipmentSlot.FEET).setUnlocalizedName("yetiBoots").setMaxStackSize(1);
        Item iceBomb = new ItemTFIceBomb().makeRare().setUnlocalizedName("iceBomb").setMaxStackSize(16);
        Item arcticFur = new ItemTF().setUnlocalizedName("arcticFur");
        Item arcticHelm = new ItemTFArcticArmor(ARMOR_ARCTIC, EntityEquipmentSlot.HEAD).setUnlocalizedName("arcticHelm").setMaxStackSize(1);
        Item arcticPlate = new ItemTFArcticArmor(ARMOR_ARCTIC, EntityEquipmentSlot.CHEST).setUnlocalizedName("arcticPlate").setMaxStackSize(1);
        Item arcticLegs = new ItemTFArcticArmor(ARMOR_ARCTIC, EntityEquipmentSlot.LEGS).setUnlocalizedName("arcticLegs").setMaxStackSize(1);
        Item arcticBoots = new ItemTFArcticArmor(ARMOR_ARCTIC, EntityEquipmentSlot.FEET).setUnlocalizedName("arcticBoots").setMaxStackSize(1);
        Item magicBeans = new ItemTFMagicBeans().setUnlocalizedName("magicBeans");
        Item giantPick = new ItemTFGiantPick(TOOL_GIANT).setUnlocalizedName("giantPick").setMaxStackSize(1);
        Item giantSword = new ItemTFGiantSword(TOOL_GIANT).setUnlocalizedName("giantSword").setMaxStackSize(1);
        Item tripleBow = new ItemTFTripleBow().setUnlocalizedName("tripleBow").setMaxStackSize(1);
        Item seekerBow = new ItemTFSeekerBow().setUnlocalizedName("seekerBow").setMaxStackSize(1);
        Item iceBow = new ItemTFIceBow().setUnlocalizedName("iceBow").setMaxStackSize(1);
        Item enderBow = new ItemTFEnderBow().setUnlocalizedName("enderBow").setMaxStackSize(1);
        Item iceSword = new ItemTFIceSword(TOOL_ICE).setUnlocalizedName("iceSword").setMaxStackSize(1);
        Item glassSword = new ItemTFGlassSword(TOOL_GLASS).setUnlocalizedName("glassSword").setMaxStackSize(1);
        Item knightmetalRing = new ItemTF().setUnlocalizedName("knightmetalRing");
        Item chainBlock = new ItemTFChainBlock().setUnlocalizedName("chainBlock").setMaxStackSize(1);
        Item cubeTalisman = new ItemTF().setUnlocalizedName("cubeTalisman");
        Item cubeOfAnnihilation = new ItemTFCubeOfAnnihilation().setUnlocalizedName("cubeOfAnnihilation").setMaxStackSize(1);

        items.register("naga_scale", nagaScale);
        items.register("naga_chestplate", plateNaga);
        items.register("naga_leggings", legsNaga);
        items.register("twilight_scepter", scepterTwilight);
        items.register("lifedrain_scepter", scepterLifeDrain);
        items.register("zombie_scepter", scepterZombie);
        //items.register(wandPacification, "Wand of Pacification [NYI]");
        items.register("ore_meter", oreMeter);
        items.register("magic_map", magicMap);
        items.register("maze_map", mazeMap);
        items.register("ore_Map", oreMap);
        items.register("raven_feather", feather);
        items.register("magic_map_focus", magicMapFocus);
        items.register("maze_map_focus", mazeMapFocus);
        items.register("liveroot", liveRoot);
        items.register("ironwood_raw", ironwoodRaw);
        items.register("ironwood_ingot", ironwoodIngot);
        items.register("ironwood_helmet", ironwoodHelm);
        items.register("ironwood_chestplate", ironwoodPlate);
        items.register("ironwood_leggings", ironwoodLegs);
        items.register("ironwood_boots", ironwoodBoots);
        items.register("ironwood_sword", ironwoodSword);
        items.register("ironwood_shovel", ironwoodShovel);
        items.register("ironwood_pickaxe", ironwoodPick);
        items.register("ironwood_axe", ironwoodAxe);
        items.register("ironwood_hoe", ironwoodHoe);
        items.register("torchberries", torchberries);
        items.register("raw_venison", venisonRaw);
        items.register("cooked_venison", venisonCooked);
        items.register("hydra_chop", hydraChop);
        items.register("fiery_blood", fieryBlood);
        items.register("trophy", trophy);
        items.register("fiery_ingot", fieryIngot);
        items.register("fiery_helmet", fieryHelm);
        items.register("fiery_chestplate", fieryPlate);
        items.register("fiery_leggings", fieryLegs);
        items.register("fiery_boots", fieryBoots);
        items.register("fiery_sword", fierySword);
        items.register("fiery_pickaxe", fieryPick);
        items.register("steeleaf_ingot", steeleafIngot);
        items.register("steeleaf_helmet", steeleafHelm);
        items.register("steeleaf_chestplate", steeleafPlate);
        items.register("steeleaf_leggings", steeleafLegs);
        items.register("steeleaf_boots", steeleafBoots);
        items.register("steeleaf_sword", steeleafSword);
        items.register("steeleaf_shovel", steeleafShovel);
        items.register("steeleaf_pickaxe", steeleafPick);
        items.register("steeleaf_axe", steeleafAxe);
        items.register("steeleaf_hoe", steeleafHoe);
        items.register("minotaur_axe", minotaurAxe);
        items.register("mazebreaker_pickaxe", mazebreakerPick);
        items.register("transformation_powder", transformPowder);
        items.register("raw_meef", meefRaw);
        items.register("cooked_meef", meefSteak);
        items.register("meef_stroganoff", meefStroganoff);
        items.register("maze_wafer", mazeWafer);
        items.register("magic_map_empty", emptyMagicMap);
        items.register("maze_map_empty", emptyMazeMap);
        items.register("ore_map_empty", emptyOreMap);
        items.register("ore_magnet", oreMagnet);
        items.register("crumble_horn", crumbleHorn);
        items.register("peacock_fan", peacockFan);
        items.register("moonworm_queen", moonwormQueen);
        items.register("charm_of_life_1", charmOfLife1);
        items.register("charm_of_life_2", charmOfLife2);
        items.register("charm_of_keeping_1", charmOfKeeping1);
        items.register("charm_of_keeping_2", charmOfKeeping2);
        items.register("charm_of_keeping_3", charmOfKeeping3);
        items.register("tower_key", towerKey);
        items.register("borer_essence", borerEssence);
        items.register("carminite", carminite);
        items.register("experiment_115", experiment115);
        items.register("armor_shard", armorShard);
        items.register("knightmetal_ingot", knightMetal);
        items.register("armor_shard_cluster", shardCluster);
        items.register("knightmetal_helmet", knightlyHelm);
        items.register("knightmetal_chestplate", knightlyPlate);
        items.register("knightmetal_leggings", knightlyLegs);
        items.register("knightmetal_boots", knightlyBoots);
        items.register("knightmetal_sword", knightlySword);
        items.register("knightmetal_pickaxe", knightlyPick);
        items.register("knightmetal_axe", knightlyAxe);
        items.register("phantom_helmet", phantomHelm);
        items.register("phantom_chestplate", phantomPlate);
        items.register("lamp_of_cinders", lampOfCinders);
        items.register("fiery_tears", fieryTears);
        items.register("alpha_fur", alphaFur);
        items.register("yeti_helmet", yetiHelm);
        items.register("yeti_chestplate", yetiPlate);
        items.register("yeti_leggings", yetiLegs);
        items.register("yeti_boots", yetiBoots);
        items.register("ice_bomb", iceBomb);
        items.register("arctic_fur", arcticFur);
        items.register("arctic_helmet", arcticHelm);
        items.register("arctic_chestplate", arcticPlate);
        items.register("arctic_leggings", arcticLegs);
        items.register("arctic_boots", arcticBoots);
        items.register("magic_beans", magicBeans);
        items.register("giant_pickaxe", giantPick);
        items.register("giant_sword", giantSword);
        items.register("triple_bow", tripleBow);
        items.register("seeker_bow", seekerBow);
        items.register("ice_bow", iceBow);
        items.register("ender_bow", enderBow);
        items.register("ice_sword", iceSword);
        items.register("glass_sword", glassSword);
        items.register("knightmetal_ring", knightmetalRing);
        items.register("block_and_chain", chainBlock);
        items.register("cube_talisman", cubeTalisman);
        items.register("cube_of_annihilation", cubeOfAnnihilation);
    }

    private static class ItemRegistryHelper {
        private final IForgeRegistry<Item> registry;

        ItemRegistryHelper(IForgeRegistry<Item> registry)
        {
            this.registry = registry;
        }

        private void register(String registryName, Item item)
        {
            item.setRegistryName(TwilightForestMod.ID, registryName);
            registry.register(item);
        }
    }
}
