@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.compat;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;