@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.worldgen.structures;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;