@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.worldgen.structures;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;