@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.compat.jei;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;