@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.entity.monster;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;