@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.worldgen.templates;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;