@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.enchantment;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;