@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;