@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.events;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;