@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.client.model.tileentity.legacy;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;