@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.loot.functions;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;