@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.compat.curios.renderer;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;