@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.capabilities.fan;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;