@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.entity;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;