@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.entity.ai;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;