@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.compat.tcon;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;