@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.compat.ie;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;