@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.compat.tcon.traits;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;