@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.world.components.structures.minotaurmaze;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;