@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.capabilities.shield;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;