@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.inventory;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;