@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.inventory.slot;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;