@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.entity.boss;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;