@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.capabilities;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;