@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.block.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;